version: "3"

services:
  web:
    build: .
    command: bash -c "pip install django==1.11 && python manage.py runsslserver 0.0.0.0:443"
    volumes:
      - .:/usr/src/app
    ports:
      - "443:443"
      # this port is for debug tools
      - "4445:4445"
